/**
 * FontAwesome 5 class name → Lucide React component name mapping.
 * Used by the Icon bridge component during the migration period.
 *
 * Pattern: strip "fas ", "far ", "fab " prefix, then map the icon name.
 * Only icons actually used in the codebase are mapped.
 */
export const FA_TO_LUCIDE = {
  // Navigation & layout
  'fa-tv': 'LayoutDashboard',
  'fa-home': 'Home',
  'fa-bars': 'Menu',
  'fa-times': 'X',
  'fa-arrow-left': 'ArrowLeft',
  'fa-arrow-right': 'ArrowRight',
  'fa-chevron-left': 'ChevronLeft',
  'fa-chevron-right': 'ChevronRight',
  'fa-chevron-down': 'ChevronDown',
  'fa-chevron-up': 'ChevronUp',
  'fa-caret-down': 'ChevronDown',
  'fa-caret-up': 'ChevronUp',
  'fa-angle-right': 'ChevronRight',
  'fa-angle-left': 'ChevronLeft',
  'fa-external-link-alt': 'ExternalLink',

  // Documents & files
  'fa-file': 'File',
  'fa-file-alt': 'FileText',
  'fa-file-invoice': 'FileSpreadsheet',
  'fa-file-import': 'FileInput',
  'fa-file-export': 'FileOutput',
  'fa-file-pdf': 'FileText',
  'fa-file-download': 'FileDown',
  'fa-file-upload': 'FileUp',
  'fa-file-signature': 'PenLine',
  'fa-file-medical-alt': 'FilePlus',
  'fa-folder': 'Folder',
  'fa-folder-open': 'FolderOpen',
  'fa-copy': 'Copy',
  'fa-paperclip': 'Paperclip',
  'fa-clipboard': 'ClipboardList',
  'fa-clipboard-check': 'ClipboardCheck',
  'fa-clipboard-list': 'ClipboardList',

  // Communication
  'fa-envelope': 'Mail',
  'fa-envelope-open-text': 'Mail',
  'fa-comment': 'MessageSquare',
  'fa-comments': 'MessageSquare',
  'fa-paper-plane': 'Send',
  'fa-bell': 'Bell',
  'fa-phone': 'Phone',

  // Calendar & time
  'fa-calendar': 'Calendar',
  'fa-calendar-alt': 'Calendar',
  'fa-calendar-check': 'CalendarCheck',
  'fa-clock': 'Clock',
  'fa-hourglass-half': 'Timer',
  'fa-history': 'History',
  'fa-stopwatch': 'Timer',
  'fa-pause': 'Pause',
  'fa-pause-circle': 'PauseCircle',
  'fa-stop-circle': 'StopCircle',

  // Actions
  'fa-plus': 'Plus',
  'fa-plus-circle': 'PlusCircle',
  'fa-minus': 'Minus',
  'fa-minus-circle': 'MinusCircle',
  'fa-edit': 'Pencil',
  'fa-pen': 'Pencil',
  'fa-trash': 'Trash2',
  'fa-trash-alt': 'Trash2',
  'fa-save': 'Save',
  'fa-download': 'Download',
  'fa-upload': 'Upload',
  'fa-search': 'Search',
  'fa-filter': 'Filter',
  'fa-sort': 'ArrowUpDown',
  'fa-sync': 'RefreshCw',
  'fa-sync-alt': 'RefreshCw',
  'fa-redo': 'Redo',
  'fa-undo': 'Undo',
  'fa-link': 'Link',
  'fa-unlink': 'Unlink',
  'fa-print': 'Printer',
  'fa-share': 'Share2',
  'fa-eye': 'Eye',
  'fa-eye-slash': 'EyeOff',
  'fa-lock': 'Lock',
  'fa-unlock': 'Unlock',
  'fa-key': 'Key',
  'fa-cog': 'Settings',
  'fa-cogs': 'Settings',
  'fa-sliders-h': 'SlidersHorizontal',

  // Status & feedback
  'fa-check': 'Check',
  'fa-check-circle': 'CheckCircle',
  'fa-times-circle': 'XCircle',
  'fa-exclamation-triangle': 'AlertTriangle',
  'fa-exclamation-circle': 'AlertCircle',
  'fa-info-circle': 'Info',
  'fa-question-circle': 'HelpCircle',
  'fa-ban': 'Ban',
  'fa-spinner': 'Loader2',

  // Users & auth
  'fa-user': 'User',
  'fa-user-circle': 'UserCircle',
  'fa-users': 'Users',
  'fa-user-plus': 'UserPlus',
  'fa-user-minus': 'UserMinus',
  'fa-user-check': 'UserCheck',
  'fa-user-tie': 'User',
  'fa-sign-in-alt': 'LogIn',
  'fa-sign-out-alt': 'LogOut',
  'fa-id-card': 'Contact',

  // Domain-specific
  'fa-newspaper': 'Newspaper',
  'fa-calculator': 'Calculator',
  'fa-book': 'Book',
  'fa-atlas': 'BookOpen',
  'fa-hard-hat': 'HardHat',
  'fa-address-book': 'Contact',
  'fa-layer-group': 'Layers',
  'fa-cube': 'Box',
  'fa-signature': 'PenLine',
  'fa-gavel': 'Gavel',
  'fa-balance-scale': 'Scale',
  'fa-building': 'Building',
  'fa-map-marker-alt': 'MapPin',
  'fa-map': 'Map',
  'fa-globe': 'Globe',
  'fa-flag': 'Flag',
  'fa-tag': 'Tag',
  'fa-tags': 'Tags',
  'fa-hashtag': 'Hash',

  // Data & charts
  'fa-chart-bar': 'BarChart3',
  'fa-chart-line': 'LineChart',
  'fa-chart-pie': 'PieChart',
  'fa-table': 'Table',
  'fa-list': 'List',
  'fa-list-alt': 'ListOrdered',
  'fa-th': 'LayoutGrid',
  'fa-columns': 'Columns',
  'fa-database': 'Database',

  // Misc
  'fa-sun': 'Sun',
  'fa-moon': 'Moon',
  'fa-star': 'Star',
  'fa-heart': 'Heart',
  'fa-image': 'Image',
  'fa-camera': 'Camera',
  'fa-code': 'Code',
  'fa-terminal': 'Terminal',
  'fa-dollar-sign': 'DollarSign',
  'fa-percent': 'Percent',
  'fa-bolt': 'Zap',
  'fa-magic': 'Wand',
  'fa-puzzle-piece': 'Puzzle',
  'fa-trophy': 'Trophy',
  'fa-thumbs-up': 'ThumbsUp',
  'fa-thumbs-down': 'ThumbsDown',

  // FUN module icons
  'fa-ellipsis-v': 'MoreVertical',
  'fa-archive': 'Archive',
  'fa-check-square': 'CheckSquare',
  'fa-pencil-ruler': 'PenTool',
  'fa-sign': 'Megaphone',
  'fa-cogs': 'Cog',
  'fa-file-contract': 'FileCheck',
  'fa-user-cog': 'UserCog',
  'fa-comment-dots': 'MessageCircle',
  'fa-search-plus': 'SearchCheck',
  'fa-briefcase': 'Briefcase',
  'fa-folder-plus': 'FolderPlus',

  // Extended mappings — icons found in codebase audit
  'fa-address-card': 'Contact',
  'fa-adjust': 'SunMoon',
  'fa-angle-double-right': 'ChevronsRight',
  'fa-arrow-circle-down': 'ArrowDownCircle',
  'fa-arrow-circle-up': 'ArrowUpCircle',
  'fa-asterisk': 'Asterisk',
  'fa-bell-on': 'BellRing',
  'fa-bookmark': 'Bookmark',
  'fa-border-all': 'Grid3x3',
  'fa-bug': 'Bug',
  'fa-calendar-times': 'CalendarX',
  'fa-car-side': 'Car',
  'fa-chart-gantt': 'GanttChart',
  'fa-circle': 'Circle',
  'fa-cloud-download-alt': 'CloudDownload',
  'fa-cloud-upload-alt': 'CloudUpload',
  'fa-comment-medical': 'MessageSquarePlus',
  'fa-compress': 'Minimize2',
  'fa-compress-arrows-alt': 'Shrink',
  'fa-equals': 'Equal',
  'fa-eraser': 'Eraser',
  'fa-exchange-alt': 'ArrowLeftRight',
  'fa-expand': 'Maximize2',
  'fa-expand-alt': 'Expand',
  'fa-expeditedssl': 'ShieldCheck',
  'fa-file-csv': 'FileSpreadsheet',
  'fa-file-medical': 'FilePlus2',
  'fa-flag-checkered': 'FlagTriangleRight',
  'fa-font': 'Type',
  'fa-globe-americas': 'Globe',
  'fa-greater-than-equal': 'ChevronsUp',
  'fa-inbox': 'Inbox',
  'fa-life-ring': 'LifeBuoy',
  'fa-list-ul': 'List',
  'fa-male': 'User',
  'fa-map-marked-alt': 'MapPin',
  'fa-map-signs': 'Signpost',
  'fa-money-check-alt': 'Receipt',
  'fa-palette': 'Palette',
  'fa-pencil-alt': 'Pencil',
  'fa-phone-alt': 'Phone',
  'fa-prescription-bottle': 'Pill',
  'fa-project-diagram': 'Network',
  'fa-question': 'HelpCircle',
  'fa-reply': 'Reply',
  'fa-reply-all': 'ReplyAll',
  'fa-road': 'Route',
  'fa-ruler': 'Ruler',
  'fa-ruler-combined': 'Ruler',
  'fa-ruler-vertical': 'Ruler',
  'fa-search-minus': 'SearchX',
  'fa-share-square': 'Share2',
  'fa-sort-down': 'ChevronDown',
  'fa-sort-up': 'ChevronUp',
  'fa-star-of-life': 'Sparkles',
  'fa-tasks': 'ListTodo',
  'fa-text-height': 'ALargeSmall',
  'fa-th-list': 'LayoutList',
  'fa-unlock-alt': 'Unlock',
  'fa-user-clock': 'UserClock',
  'fa-user-graduate': 'GraduationCap',
  'fa-vector-square': 'Square',
  'fa-whatsapp': 'MessageCircle',

  // Additional icons (FA Regular + misc)
  'fa-window-close': 'SquareX',
  'fa-id-badge': 'BadgeCheck',
  'fa-file-word': 'FileText',
  'fa-file-excel': 'FileSpreadsheet',
  'fa-wpforms': 'FormInput',
  'fa-toolbox': 'Wrench',
};
