
export const defaultTableData = (initialData, time) => {

    const baseData = [
        {
            action: "CRAD",
            repeat: "1",
            directedTo: "Peticionario",
            day_available: "",
            date_set: null,
            useAction: true,
            cub: "",
            date_end: null,
            day_end: "1",
            isSentVerified: false,
            indicadorProceso: "",
            terminoResolver: "Fecha de inicio",
            date_setResolver: "",
        },
        {
            action: "ACLP",
            repeat: "",
            directedTo: "Peticionario",
            day_available: "",
            date_set: null,
            useAction: false,
            cub: "",
            date_end: null,
            day_end: "",
            isSentVerified: true,
            indicadorProceso: "",
            terminoResolver: "Fecha máxima",
            date_setResolver: "",
        },
        {
            action: "TPCO",
            repeat: "1",
            directedTo: "Entidades",
            day_available: "",
            date_set: null,
            useAction: false,
            cub: "",
            date_end: null,
            day_end: "",
            isSentVerified: true,
            indicadorProceso: "",
            terminoResolver: "Fecha envió respuesta",
            date_setResolver: "",
        },
        {
            action: "CTPC",
            repeat: "",
            directedTo: "Entidades",
            day_available: "",
            date_set: null,
            useAction: false,
            cub: "",
            date_end: null,
            day_end: "",
            isSentVerified: true,
            indicadorProceso: "",
            terminoResolver: "Número de días",
            date_setResolver: "",
        },
        {
            action: "AMPT",
            repeat: "",
            directedTo: "Peticionario",
            day_available: "",
            date_set: null,
            useAction: false,
            cub: "",
            date_end: null,
            day_end: "",
            isSentVerified: false,
            indicadorProceso: "",
            terminoResolver: "Eficiencia",
            date_setResolver: "",
        },
        {
            action: "REPT",
            repeat: "1",
            directedTo: "Peticionario",
            day_available: "",
            date_set: null,
            useAction: true,
            cub: "",
            date_end: null,
            day_end: "15",
            isSentVerified: false,
            indicadorProceso: "ABIERTA",
            terminoResolver: "EFICIENTE",
            date_setResolver: "",
        },
    ];
    return initialData ? baseData.map((defaultItem) => {
        const foundItem = initialData.find((item) => item.action === defaultItem.action && item.action);
        return {
            ...defaultItem,
            day_available: time && time[defaultItem.action] ? time[defaultItem.action] : defaultItem.day_available,
            ...foundItem,
        };
    }) : baseData;;
}