import {
  ALargeSmall,
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDownCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRight,
  Asterisk,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  Camera,
  Car,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  ChevronsUp,
  Circle,
  CircleAlert,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudDownload,
  CloudUpload,
  Code,
  Cog,
  Columns,
  Compass,
  Construction,
  Contact,
  Copy,
  Database,
  DollarSign,
  Download,
  Edit,
  Equal,
  Eraser,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileDown,
  FileEdit,
  FileInput,
  FileOutput,
  FilePlus,
  FilePlus2,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileUp,
  Filter,
  Flag,
  FlagTriangleRight,
  Folder,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FormInput,
  GanttChart,
  Gavel,
  Globe,
  GraduationCap,
  Grid3x3,
  HandMetal,
  HardHat,
  Hash,
  Heading3,
  Heart,
  HelpCircle,
  Highlighter,
  History,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  Italic,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LifeBuoy,
  LineChart,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareText,
  Minimize2,
  Minus,
  MinusCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Network,
  Newspaper,
  Palette,
  Paperclip,
  Pause,
  PauseCircle,
  PenLine,
  PenTool,
  Pencil,
  PencilRuler,
  Percent,
  Phone,
  PieChart,
  Pill,
  Plus,
  PlusCircle,
  Printer,
  Puzzle,
  Quote,
  Receipt,
  Redo,
  RefreshCw,
  Reply,
  ReplyAll,
  Route,
  Ruler,
  Save,
  Scale,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shrink,
  Signpost,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareX,
  Star,
  StopCircle,
  Strikethrough,
  Sun,
  SunMoon,
  Table,
  Tag,
  Tags,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TimerReset,
  Trash2,
  Trophy,
  Type,
  Underline,
  Undo,
  Unlink,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserMinus,
  UserPlus,
  UserRoundCheck,
  Users,
  Wand,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';
import { FA_TO_LUCIDE } from '@/lib/icon-map';

const LUCIDE_ICON_REGISTRY = {
  ALargeSmall,
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDownCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRight,
  Asterisk,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  Camera,
  Car,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  ChevronsUp,
  Circle,
  CircleAlert,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudDownload,
  CloudUpload,
  Code,
  Cog,
  Columns,
  Compass,
  Construction,
  Contact,
  Copy,
  Database,
  DollarSign,
  Download,
  Edit,
  Equal,
  Eraser,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileDown,
  FileEdit,
  FileInput,
  FileOutput,
  FilePlus,
  FilePlus2,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileUp,
  Filter,
  Flag,
  FlagTriangleRight,
  Folder,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FormInput,
  GanttChart,
  Gavel,
  Globe,
  GraduationCap,
  Grid3x3,
  HandMetal,
  HardHat,
  Hash,
  Heading3,
  Heart,
  HelpCircle,
  Highlighter,
  History,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  Italic,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LifeBuoy,
  LineChart,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map: MapIcon,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareText,
  Minimize2,
  Minus,
  MinusCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Network,
  Newspaper,
  Palette,
  Paperclip,
  Pause,
  PauseCircle,
  PenLine,
  PenTool,
  Pencil,
  PencilRuler,
  Percent,
  Phone,
  PieChart,
  Pill,
  Plus,
  PlusCircle,
  Printer,
  Puzzle,
  Quote,
  Receipt,
  Redo,
  RefreshCw,
  Reply,
  ReplyAll,
  Route,
  Ruler,
  Save,
  Scale,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shrink,
  Signpost,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareX,
  Star,
  StopCircle,
  Strikethrough,
  Sun,
  SunMoon,
  Table,
  Tag,
  Tags,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TimerReset,
  Trash2,
  Trophy,
  Type,
  Underline,
  Undo,
  Unlink,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserMinus,
  UserPlus,
  UserRoundCheck,
  Users,
  Wand,
  Wrench,
  X,
  XCircle,
  Zap,
};

const LEGACY_ICON_ALIASES = {
  'search-location': 'MapPin',
  exclamation: 'CircleAlert',
  'circle-nodes': 'Network',
};

function normalizeIconName(name) {
  if (!name) return null;

  const rawName = String(name).trim();
  if (!rawName) return null;

  if (LEGACY_ICON_ALIASES[rawName]) {
    return LEGACY_ICON_ALIASES[rawName];
  }

  if (FA_TO_LUCIDE[rawName]) {
    return FA_TO_LUCIDE[rawName];
  }

  if (LUCIDE_ICON_REGISTRY[rawName]) {
    return rawName;
  }

  const tokens = rawName.split(/\s+/).filter(Boolean);
  const faToken = tokens.find((token) => token.startsWith('fa-'));

  if (faToken && FA_TO_LUCIDE[faToken]) {
    return FA_TO_LUCIDE[faToken];
  }

  const legacyName = rawName.startsWith('fa-') ? rawName : `fa-${rawName}`;
  if (FA_TO_LUCIDE[legacyName]) {
    return FA_TO_LUCIDE[legacyName];
  }

  return rawName;
}

/**
 * Bridge component: accepts a FontAwesome class name or curated Lucide component name
 * and renders the corresponding Lucide React icon without importing the full icon pack.
 *
 * Usage:
 *   <Icon name="fa-file-alt" />           // FA name
 *   <Icon name="FileText" />              // registered Lucide name
 *   <Icon name="fa-file-alt" size={20} /> // with size
 *   <Icon name="fa-file-alt" className="text-primary" />
 *
 * @param {object} props
 * @param {string} props.name - FA class name (e.g. "fa-file-alt") or registered Lucide name (e.g. "FileText")
 * @param {number} [props.size=16] - Icon size in px
 * @param {string} [props.className] - CSS classes
 */
export function Icon({ name, size = 16, className, ...rest }) {
  const lucideName = normalizeIconName(name);
  const LucideComponent = LUCIDE_ICON_REGISTRY[lucideName] || CircleAlert;

  return <LucideComponent size={size} className={className} {...rest} />;
}

export default Icon;
